using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Serialization;

namespace Datafeeds
{
    /// <summary>
    /// Provide deserialization of the given XML 
    /// </summary>
    /// <typeparam name="T">Root Class of XML model generated by XSD.exe from from the given XML class.</typeparam>
    public class XmlDeserializator<T>
    {
        XmlSerializer serializer;

        public XmlDeserializator()
        {
            serializer = new XmlSerializer(typeof(T));
        }

        public T deserialize(string xml)
        {
            TextReader reader = new StringReader(xml);
            T result = (T)serializer.Deserialize(reader);
            reader.Close();
            return result;
        }

        public T deserializeFile(string path)
        {            
            return deserialize(File.ReadAllText(path));
        }
    }
}
